server:
  port: 8081
  servlet:    context-path: /contact-app
spring:  mvc:    view:      prefix:  /WEB-INF/pages/
      suffix: .jsp
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cts_db
    username: root
    password: root
    